/** Single import surface for section/concept authors. */
export { registerConcept, getConcept, allConceptIds } from "./registry";
export type { ConceptDef, ConceptId } from "./types";
export { TooltipProvider, ConceptLink } from "./tooltip/TooltipEngine";
export type { TooltipLabels } from "./tooltip/TooltipEngine";
export { ExpandedReading } from "./ExpandedReading";
export { M, MD, Eq, EnvBlock } from "./Math";
export { Quiz, Frage, QuizLabelsProvider } from "./Quiz";
export type { QuizLabels } from "./Quiz";
export { Slider } from "./widgets/Slider";
export { MatrixInput } from "./widgets/MatrixInput";
export { TransformCanvas } from "./widgets/TransformCanvas";
export type { Vec2 } from "./widgets/TransformCanvas";
export { Plot } from "./widgets/Plot";
export type { Series } from "./widgets/Plot";
export { LabeledPlot, LabeledTransformCanvas, niceTicks, sigmaMax, maxAbsCoord } from "./widgets/Axes";
export { ConceptFlow } from "./widgets/ConceptFlow";
export type { FlowNode, FlowEdge, FlowGroup } from "./widgets/ConceptFlow";
export { Proof, PStep, ProofLabelsProvider } from "./Proof";
export type { ProofLabels } from "./Proof";
export { FMM_COLORS, fmtDe, fmtInt, clamp, mulberry32, randn, useSeed, fmtTick } from "./widgets/util";
