import { useMemo, useState } from "react";
import { Aufgabe, FMM_COLORS, Slider, Surface3D, Verdikt, ViewControls, fmtDe } from "../../../lib";
import type { Sicht3D } from "../../../lib";
/**
 * Einsicht: Der gemischte Koeffizient c22 koppelt x und y; ohne ihn bleibt die
 * Fläche eine Ebene. Farbrollen: erster Faktor x blau, zweiter Faktor y grün,
 * Koeffizienten orange, Funktionswerte violett (keine Kollision). Eigenbau.
 * Per node verifiziert: für 2+3x−y+5xy sind die Eckwerte 2,5,1,9 und c22=5
 * (verify-09-tensoren/check-s94.mjs, 2026-08-19).
 */
const {blau:B,gruen:G,orange:O,violett:V,grau:N}=FMM_COLORS;
type K={a:number;b:number;c:number;d:number}; const f=(k:K,x:number,y:number)=>k.a+k.b*x+k.c*y+k.d*x*y;
export function TensorbasisExplorer(){const [k,setK]=useState<K>({a:2,b:3,c:-1,d:5});const [sicht,setSicht]=useState<Sicht3D>({azimuth:38,elevation:26});const surface=useMemo(()=>({f:(x:number,y:number)=>f(k,x,y),nx:22,ny:22,color:V,opacity:.82,wire:true}),[k]);const e=[f(k,0,0),f(k,1,0),f(k,0,1),f(k,1,1)],lo=Math.min(...e),hi=Math.max(...e);return <div><Aufgabe>Verändern wir c₂₂ und vergleichen wir Heatmap und dieselbe Fläche im Raum.</Aufgabe><div className="max-w-md">{([['a','c₁₁'],['b','c₂₁'],['c','c₁₂'],['d','c₂₂']] as const).map(([id,label])=><Slider key={id} label={label} value={k[id]} onChange={v=>setK({...k,[id]:v})} min={-5} max={5} step={.5} accent={O}/>)}</div><button type="button" className="rounded px-2 py-1 text-sm" onClick={()=>setK({...k,d:0})}>c₂₂ auf 0 setzen</button><div className="mt-3 flex flex-wrap gap-4 items-start"><svg viewBox="0 0 260 260" className="max-w-full h-auto" role="img" aria-label="Heatmap der Tensorproduktfunktion über dem Einheitsquadrat.">{Array.from({length:20},(_,i)=>Array.from({length:20},(_,j)=>{const z=f(k,(i+.5)/20,(j+.5)/20),t=(z-lo)/(hi-lo||1);return <rect key={`${i}-${j}`} x={20+i*10} y={20+(19-j)*10} width="10.4" height="10.4" fill={V} fillOpacity={.12+.78*t}/> }))}<rect x="20" y="20" width="200" height="200" fill="none" stroke={N}/><text x="120" y="245" fill={B}>x</text><text x="8" y="125" fill={G}>y</text></svg><Surface3D size={280} xDomain={[0,1]} yDomain={[0,1]} zDomain={[lo,hi]} surface={surface} points={[{p:[1,1,e[3]],color:O,label:"f(1,1)"}]} azimuth={sicht.azimuth} elevation={sicht.elevation} onViewChange={setSicht} labels={{x:"x",y:"y",z:"f"}} ariaLabel="Dieselbe Tensorproduktfunktion als dreidimensionale Fläche."/></div><ViewControls value={sicht} onChange={setSicht}/><Verdikt kind={Math.abs(k.d)<1e-9?"ok":"neutral"}>{Math.abs(k.d)<1e-9?"c₂₂ ist null: Die Steigung in x hängt nicht von y ab; nach Bemerkung 9.4.13 ist die Fläche eine Ebene.":`Die Eckwerte ${e.map(x=>fmtDe(x,1)).join(", ")} ergeben c₂₂ = ${fmtDe(e[3]-e[1]-e[2]+e[0],1)}. Der gemischte Term koppelt die Variablen (Bemerkung 9.4.13).`}</Verdikt></div>}
