#!/usr/bin/env node
/**
 * Generate src/fmm-macros.ts from the course's MathJax macro file
 * (fmm-lmu/slides/_mathjax-macros.qmd — the single source of truth).
 *
 *   node scripts/gen-macros.mjs ../fmm-lmu/slides/_mathjax-macros.qmd
 *
 * Parses \newcommand{\name}{def}, \newcommand{\name}[n]{def} and
 * \definecolor{name}{RGB}{r,g,b} into a MathJax `macros` map plus a
 * bootstrap TeX string that registers the named colors at runtime.
 */
import { readFileSync, writeFileSync } from "node:fs";

const src = readFileSync(process.argv[2] ?? "../fmm-lmu/slides/_mathjax-macros.qmd", "utf8");

/** Return the brace-balanced group starting at src[i] === "{". */
function group(s, i) {
  if (s[i] !== "{") throw new Error(`expected { at ${i}: ${s.slice(i, i + 30)}`);
  let depth = 0;
  for (let j = i; j < s.length; j++) {
    if (s[j] === "{") depth++;
    else if (s[j] === "}") {
      depth--;
      if (depth === 0) return { body: s.slice(i + 1, j), end: j + 1 };
    }
  }
  throw new Error("unbalanced braces");
}

const macros = {};
const colors = [];
const re = /\\(newcommand|definecolor)/g;
let m;
while ((m = re.exec(src)) !== null) {
  let i = m.index + m[0].length;
  if (m[1] === "definecolor") {
    const name = group(src, i);
    const model = group(src, name.end);
    const spec = group(src, model.end);
    colors.push({ name: name.body, model: model.body, spec: spec.body });
    continue;
  }
  const name = group(src, i); // {\name}
  i = name.end;
  let nargs = 0;
  const argm = /^\[(\d)\]/.exec(src.slice(i));
  if (argm) {
    nargs = Number(argm[1]);
    i += argm[0].length;
  }
  const def = group(src, i);
  const key = name.body.replace(/^\\/, "");
  macros[key] = nargs > 0 ? [def.body, nargs] : def.body;
}

// MathJax-only overrides: the source's \cb* helpers wrap their argument in
// \textbf, which switches MathJax into TEXT mode — any \boldsymbol inside
// the argument (\bA, \bx, ...) then errors. \boldsymbol itself bolds the
// whole (math) argument, which is what the slides mean.
const CB_OVERRIDES = {
  cb: ["{\\boldsymbol{#1}}", 1],
  cbgreen: ["{\\textcolor{fmmgreen}{\\boldsymbol{#1}}}", 1],
  cbred: ["{\\textcolor{fmmred}{\\boldsymbol{#1}}}", 1],
  cbpurp: ["{\\textcolor{fmmpurple}{\\boldsymbol{#1}}}", 1],
  cborange: ["{\\textcolor{fmmorange}{\\boldsymbol{#1}}}", 1],
};
Object.assign(macros, CB_OVERRIDES);

const colorBootstrap = colors
  .map((c) => `\\definecolor{${c.name}}{${c.model}}{${c.spec}}`)
  .join(" ");

const out = `/**
 * GENERATED by scripts/gen-macros.mjs from fmm-lmu/slides/_mathjax-macros.qmd
 * — do not edit by hand; regenerate when the course macros change.
 * ${Object.keys(macros).length} macros, ${colors.length} named colors.
 */
export const fmmMacros: Record<string, string | [string, number]> = ${JSON.stringify(macros, null, 2)};

/** TeX run once at startup so the named FMM colors exist document-wide. */
export const fmmColorBootstrap = ${JSON.stringify(colorBootstrap)};
`;
writeFileSync(new URL("../src/fmm-macros.ts", import.meta.url), out);
console.log(`generated: ${Object.keys(macros).length} macros, ${colors.length} colors`);
